export const ROUTES = {
  HOME: "/",
  LOGIN: "/login",
  SIGNUP: "/signup",
  PRODUCTS: "/products",
  PRODUCT_DETAILS: (id: string | number = ":id") => `/product-details/${id}`,
  GIFTCARD_DETAILS: (id: string | number = ":id") => `/giftcard/${id}`,
  CREATE_DESIGN: "/createYourDesign",
  CREATE_DESIGN_DETAIL: (id: string | number = ":id") => `/createYourDesign/${id}`,
  DESIGN_LAB: "/design-lab",
  COMPARE: "/compare",
  RENTAL: "/rental",
  RENTAL_SHOP: "/rental/shop",
  RENTAL_PRODUCT_DETAILS: (id: string | number = ":id") => `/rental/shop/${id}`,
  COLLECTIONS: (category: string = ":category") => `/collections/${category}`,
  BAG: "/bag",
  CHECKOUT: "/checkout",
  WHOLESALE: "/wholesale",
  WHOLESALE_DETAILS: (id: string | number = ":id") => `/wholesale/${id}`,
  WHOLESALE_BAG: "/wholesale-bag",
  WHOLESALE_CHECKOUT: "/wholesale-checkout",
  DROPSHIPPING: "/dropshipping",
  FAVORITES: "/favorites",
  TERMS: "/terms",
  PRIVACY: "/privacy",

  // User Dashboard
  USER_DASHBOARD: "/dashboard/user",
  USER_RECENTLY_VIEWED: "/recently-viewed",
  USER_CONTACT_DETAILS: "/contact-details",
  USER_NOTIFICATIONS: "/notifications",
  USER_NOTIFY_ME: "/notify-me-list",
  USER_SETTINGS: "/settings",
  USER_ORDERS: "/my-orders",
  USER_GIFT_CARDS: "/my-gift-cards",
  USER_HELP_CENTER: "/help-center",
  USER_WALLET_REWARDS: "/wallet-rewards",
  USER_PRIZE_WHEEL: "/prize-wheel",

  // Trader Dashboard
  TRADER_LOGIN: "/trader/login",
  TRADER_DASHBOARD: "/dashboard/trader",
  TRADER_CATEGORIES: "/dashboard/trader/categories",
  TRADER_PRODUCTS: "/dashboard/trader/products",
  TRADER_ORDERS: "/dashboard/trader/orders",
  TRADER_CUSTOMERS: "/dashboard/trader/customers",
  TRADER_COUPONS: "/dashboard/trader/coupons",
  TRADER_COLLECTIONS: "/dashboard/trader/collections",
  TRADER_INFLUENCERS: "/dashboard/trader/influencers",
  TRADER_DESIGNS: "/dashboard/trader/designs",
  TRADER_WEBSITE_SETTINGS: "/dashboard/trader/website-settings",
  TRADER_PREFERENCES: "/dashboard/trader/preferences",
  TRADER_FINANCE: "/dashboard/trader/finance",
  TRADER_NOTIFICATIONS: "/dashboard/trader/notifications",
  TRADER_PRIZES: "/dashboard/trader/prizes",
  TRADER_RENTAL: "/dashboard/trader/rental",
  TRADER_BLANK_PRODUCTS: "/dashboard/trader/blank-products",
  TRADER_INVENTORY: "/dashboard/trader/inventory",
  TRADER_ANALYTICS: "/dashboard/trader/analytics",
  TRADER_DROPSHIPPING: "/dashboard/trader/dropshipping",

  // Influencer Dashboard
  INFLUENCER_LOGIN: "/influencer/login",
  INFLUENCER_DASHBOARD: "/dashboard/influencer",
  INFLUENCER_COUPON_USERS: "/dashboard/influencer/coupon-users",
  INFLUENCER_EARNINGS: "/dashboard/influencer/earnings",
} as const;

export default ROUTES;
